export const myQuestions = [
  {
    answers: {
      answer_a: "10 μ",
      answer_b: "11 μ",
      answer_c: "9 μ",
      answer_d: "12 μ",
    },
    category: "1",
    correct_answer: null,
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "true",
      answer_c_correct: "false",
      answer_d_correct: "false",
    },
    description: null,
    difficulty: "easy",
    explanation: "Σύμφωνα με τον αντίστοιχο κανόνα",
    id: 1,
    multiple_correct_answers: "false",
    question:
      "Ποια είναι η απόσταση του σημείου του πέναλτι από τη γραμμή του τέρματος;",
    tags: [{ name: "Ο αγωνιστικός χώρος" }],
    tip: null,
  },
  {
    answers: {
      answer_a: "απαραίτητα.",
      answer_b: "απαραίτητα μόνο για διεθνείς αγώνες.",
      answer_c: "προαιρετικά.",
      answer_d: "απαραίτητα, αν το προβλέπει ο κανονισμός της διοργάνωσης.",
    },
    category: "1",
    correct_answer: null,
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
    },
    description: null,
    difficulty: "medium",
    explanation: "Σύμφωνα με τον αντίστοιχο κανόνα",
    id: 2,
    multiple_correct_answers: "false",
    question: "Τα κοντάρια με σημαία που τοποθετούνται στο κόρνερ είναι...",
    tags: [{ name: "Ο αγωνιστικός χώρος" }],
    tip: null,
  },
  {
    answers: {
      answer_a: "7,32 μ",
      answer_b: "9,15 μ",
      answer_c: "11 μ",
      answer_d: "2,44 μ",
    },
    category: "1",
    correct_answer: null,
    correct_answers: {
      answer_a_correct: "true",
      answer_b_correct: "false",
      answer_c_correct: "false",
      answer_d_correct: "false",
    },
    description: null,
    difficulty: "medium",
    explanation: "Σύμφωνα με τον αντίστοιχο κανόνα",
    id: 3,
    multiple_correct_answers: "false",
    question: "Η απόσταση μεταξύ των κάθετων δοκών πρέπει να είναι...",
    tags: [{ name: "Ο αγωνιστικός χώρος" }],
    tip: null,
  },
  {
    answers: {
      answer_a: "9,15 μέτρα",
      answer_b: "1 μέτρο",
      answer_c: "12 εκ",
      answer_d: "5,5 μέτρα",
    },
    category: "1",
    correct_answer: null,
    correct_answers: {
      answer_a_correct: "false",
      answer_b_correct: "true",
      answer_c_correct: "false",
      answer_d_correct: "false",
    },
    description: null,
    difficulty: "easy",
    explanation: "Σύμφωνα με τον αντίστοιχο κανόνα",
    id: 4,
    multiple_correct_answers: "false",
    question:
      "Η ακτίνα του γωνιαίου τόξου, που χαράσσεται στο εσωτερικό τμήμα του αγωνιστικού χώρου είναι...",
    tags: [{ name: "Ο αγωνιστικός χώρος" }],
    tip: null,
  },
];
